name = "Tella"
license = "MIT"
licenselink = "https://github.com/opera7133/tella/blob/master/LICENSE"
description = "Simple, Light, Responsive"
homepage = "https://github.com/opera7133/tella
tags = ["light", "simple", "blog", "clean", "tailwindcss", "responsive"]
features = [""]
min_version = "0.69"

[author]
  name = "wamo"
  homepage = "https://wmsci.com"
